import jsPDF from 'jspdf';
import { Game, Team, Player, StatsLog } from '@/types';

interface PlayerRow {
  num:   string;
  pts:   number;
  fg2:   number; fg2a: number;
  fg3:   number; fg3a: number;
  ft:    number; fta:  number;
  orbd:  number; drbd: number;
  ast:   number; stl:  number;
  blk:   number; tov:  number;
  foul:  number;
}

function buildPlayerRows(
  players: Player[],
  logs: StatsLog[],
  teamId: string,
): PlayerRow[] {
  return players
    .filter((p) => p.team_id === teamId)
    .map((p) => {
      const pl = logs.filter((l) => l.player_id === p.id && !l.is_deleted);
      const count = (t: string) => pl.filter((l) => l.action_type === t).length;
      return {
        num:  p.back_number,
        pts:  count('2PT_MADE') * 2 + count('3PT_MADE') * 3 + count('FT_MADE'),
        fg2:  count('2PT_MADE'), fg2a: count('2PT_MADE') + count('2PT_MISS'),
        fg3:  count('3PT_MADE'), fg3a: count('3PT_MADE') + count('3PT_MISS'),
        ft:   count('FT_MADE'),  fta:  count('FT_MADE')  + count('FT_MISS'),
        orbd: count('ORBD'),     drbd: count('DRBD'),
        ast:  count('AST'),      stl:  count('STL'),
        blk:  count('BLK'),      tov:  count('TOV'),
        foul: count('FOUL'),
      };
    })
    .filter((r) => r.pts + r.fg2a + r.fg3a + r.fta + r.orbd + r.drbd + r.ast + r.stl + r.blk + r.tov + r.foul > 0)
    .sort((a, b) => Number(a.num) - Number(b.num));
}

function periodScore(logs: StatsLog[], teamId: string, period: number): number {
  return logs
    .filter((l) => l.team_id === teamId && l.period === period && !l.is_deleted)
    .reduce((s, l) => s + l.points, 0);
}

export function generateGamePDF(
  game: Game,
  ourTeam: Team,
  theirTeam: Team,
  allPlayers: Player[],
  logs: StatsLog[],
  ourScore: number,
  theirScore: number,
): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  let y = 15;

  const line  = (x1: number, y1: number, x2: number, y2: number) => doc.line(x1, y1, x2, y2);
  const text  = (t: string, x: number, ty: number, size = 10, style: 'normal' | 'bold' = 'normal') => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.text(t, x, ty);
  };
  const rtext = (t: string, x: number, ty: number, size = 10) => {
    doc.setFontSize(size); doc.setFont('helvetica', 'normal');
    doc.text(t, x, ty, { align: 'right' });
  };

  // ── タイトル ──
  text('BASKETBALL GAME STATS REPORT', W / 2, y, 14, 'bold');
  doc.setFontSize(10);
  doc.text(game.game_name, W / 2, y + 7, { align: 'center' });
  doc.text(game.date, W / 2, y + 13, { align: 'center' });
  y += 20;

  // ── スコア ──
  line(10, y, W - 10, y); y += 7;
  text(ourTeam.team_name || 'A',  30, y, 12, 'bold');
  text(`${ourScore}`, 80, y, 20, 'bold');
  text('-', W / 2, y, 16, 'bold');
  text(`${theirScore}`, W - 80, y, 20, 'bold');
  text(theirTeam.team_name || 'B', W - 30, y, 12, 'bold');
  y += 12;
  line(10, y, W - 10, y); y += 5;

  // ── クォーター別 ──
  const periods = [1, 2, 3, 4];
  text('Quarter', 12, y, 9, 'bold');
  periods.forEach((p, i) => text(`${p}Q`, 45 + i * 15, y, 9, 'bold'));
  text('Total', 110, y, 9, 'bold');
  y += 5;

  [ourTeam, theirTeam].forEach((team, ti) => {
    const scores = periods.map((p) => periodScore(logs, team.id, p));
    const total  = ti === 0 ? ourScore : theirScore;
    text(team.team_name || (ti === 0 ? 'A' : 'B'), 12, y, 9);
    scores.forEach((s, i) => text(`${s}`, 45 + i * 15, y, 9));
    text(`${total}`, 110, y, 9, 'bold');
    y += 6;
  });
  y += 3;

  // ── プレイヤースタッツ ──
  const drawTeamStats = (team: Team) => {
    const rows = buildPlayerRows(allPlayers, logs, team.id);
    if (rows.length === 0) return;

    line(10, y, W - 10, y);
    y += 6;
    text(`${team.team_name || 'Team'} — Player Stats`, 12, y, 10, 'bold');
    y += 6;

    // ヘッダー行
    const cols = ['#', 'PTS', '2PM', '2PA', '3PM', '3PA', 'FTM', 'FTA', 'OR', 'DR', 'AST', 'STL', 'BLK', 'TOV', 'FOUL'];
    const xs   = [12, 25, 38, 48, 58, 68, 78, 88, 98, 106, 114, 122, 130, 138, 148];
    doc.setFontSize(7); doc.setFont('helvetica', 'bold');
    cols.forEach((c, i) => doc.text(c, xs[i], y));
    y += 1; line(10, y, W - 10, y); y += 4;

    rows.forEach((r) => {
      doc.setFontSize(8); doc.setFont('helvetica', 'normal');
      const vals = [r.num, r.pts, r.fg2, r.fg2a, r.fg3, r.fg3a, r.ft, r.fta, r.orbd, r.drbd, r.ast, r.stl, r.blk, r.tov, r.foul];
      vals.forEach((v, i) => doc.text(String(v), xs[i], y));
      y += 5;
    });
    y += 4;
  };

  drawTeamStats(ourTeam);
  drawTeamStats(theirTeam);

  // フッター
  line(10, y, W - 10, y); y += 5;
  text(`Generated by Basketball Score App — ${new Date().toLocaleString('ja-JP')}`, W / 2, y, 7);

  doc.save(`${game.game_name}_${game.date}.pdf`);
}
